/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

//-----------------------------
//Includes
//-----------------------------

#include "STM32F103xx6.h"
#include "STM32F103C6_EXTI_DRIVER.h"
#include "STM32F103C6_GPIO_DRIVER.h"
#include "STM32F103C6_RCC_DRIVER.h"
#include "STM32F103C6_I2C_DRIVER.h"
#include "I2C_Slave_EEPROM.h"


void Clock_Init(void);


int main(void)
{
	Clock_Init();


	/*----------------------------Test Case1-------------------------------*/
	unsigned char Write_Data[] = {0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7};
	unsigned char Read_Data[7] = {0};

	EEPROM_INITIALIZE();
	EEPROM_Write_NBytes(0xAF, Write_Data, 7);
	EEPROM_Read_NBytes(0xAF, Read_Data, 7);


	/*----------------------------Test Case2-------------------------------*/
	Write_Data[0] = 0xA;
	Write_Data[1] = 0xB;
	Write_Data[2] = 0xC;
	Write_Data[3] = 0xD;

	EEPROM_Write_NBytes(0xFFF, Write_Data, 4);
	EEPROM_Read_NBytes(0xFFF, Read_Data, 4);


	/* Loop forever */
	while(1)
	{
	}
}

void Clock_Init()
{
	//open clock of AFIO
	RCC_AFIO_CLK_EN();

	//open clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//open clock of GPIOB
	RCC_GPIOB_CLK_EN();
}
