/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include"STM32F103xx6.h"
#include"STM32F103C6_GPIO_DRIVER.h"

void Clock_Init()
{
	//	enable clock GPIOA
	RCC_GPIOA_CLK_EN();
	//	enable clock GPIOB
	RCC_GPIOB_CLK_EN();
}

void GPIO_Init()
{
	GPIO_PinConfig_t PinCfg;

	//	Pin 1 port A input high Z floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//	Pin 1 Port B Push-Pull output
	//	01: Output mode, max speed 10 MHz.
	//	00: General purpose output push-pull
	PinCfg.GPIO_PinNumber=GPIO_PIN_1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	//	===================================================
	//	Pin 13 port A input high Z floating input (reset state)
	PinCfg.GPIO_PinNumber = GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	//	Pin 13 port B Push-Pull 01: Output mode, max speed 10 MHz. output
	//	01: Output mode, max speed 10 MHz.
	//	00: General purpose output push-pull
	PinCfg.GPIO_PinNumber=GPIO_PIN_13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);


}
void wait(uint32_t time)
{

	uint32_t i,j;
	for (i =0; i<time;i++)
	{
		for (j=0 ; j<255;j++)
		{
			;
		}
	}

}

int main(void)
{
	Clock_Init();
	GPIO_Init();

	while(1)
	{
		//		pull up resistance
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) ==0)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			//			single press
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) ==0);
		}
		//		pull down resistance
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)
		{
			//			multi press
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
		}
		wait(1);

	}
}

