/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
typedef volatile unsigned int vuint32_t;

//RCC register
#define RCC_BASE 		0x40021000
#define RCC_APB2ENR 	*(volatile uint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPEN		(1 << 2)
//GPIO register
#define GPIOA_BASE 		0x40010800
#define GPIOA_CRH 		*(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR 		*(volatile uint32_t *)(GPIOA_BASE + 0x0C)

#define EXTI_BASE 		0x40010400
#define EXTI_IMR		*(volatile uint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR		*(volatile uint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR			*(volatile uint32_t *)(EXTI_BASE + 0x14)

#define AFIO_BASE 		0x40010000
#define AFIO_EXTICR1	*(volatile uint32_t *)(AFIO_BASE + 0x08)

#define NVIC_ISER0		*(volatile uint32_t *)(0xE000E100)

void Clock_Init()
{
	//	enable clock GPIOA
	RCC_APB2ENR |= RCC_IOPEN;

	//	Bit 0 AFIOEN: Alternate function I/O clock enable
	RCC_APB2ENR |= (1<<0);
}
void GPIO_Init()
{
	//	Pin 13 port A output
	GPIOA_CRH &= 0xff0fffff;
	GPIOA_CRH |= 0x00200000;

	//	PinA0 01: Floating input (reset state)
	GPIOA_CRH |= (1<<2);
}
int main(void)
{
	//	configure EXTI0 to portA0
	AFIO_EXTICR1 = 0;

	//	Enable EXTI line 0
	EXTI_IMR |= (1<< 0);

	//	Enable rising edge trigger
	EXTI_RTSR |= (1<< 0);

	//	Enable NVIC IRQ6
	NVIC_ISER0 |= 1<<6;
}

void EXTI0_IRQHandler(void)
{
	//	IRQ is happened EXTI0 >>> PORTA pin 0 rising edge
	//	toggle pin 13
	GPIOA_ODR ^= 1<<13;

	//	clear pending register
	EXTI_PR |= 1 <<0;
}
