/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "STM32F103xx6.h"
#include "STM32F103C6_GPIO_DRIVER.h"
#include "STM32F103C6_USART_DRIVER.h"

void Clock_Init(void);
void UART_IRQ_CallBack(void);


uint8_t ch;

int main(void)
{
	Clock_Init();


	//	UART_Configuration_t UART_CFG;
	//	UART_CFG.UART_MODE = UART_MODE_Tx_Rx;
	//	UART_CFG.UART_Payload_length = UART_Payload_length_8B;
	//	UART_CFG.UART_Num_Stop_Bits = UART_Num_Stop_Bits_one_bit;
	//	UART_CFG.UART_Parity = UART_Parity_NONE;
	//	UART_CFG.UART_BaudRate = UART_BaudRate_115200;
	//	UART_CFG.UART_HW_FLOW_CTL = UART_HW_FLOW_CTL_NONE;
	//	UART_CFG.UART_IRQ_Enable = UART_IRQ_Enable_NONE;
	//	UART_CFG.UART_PF_IRQ_CallBack = NULL;
	//
	//	MCAL_UART_Init(USART1, &UART_CFG);
	//	MCAL_UART_GPIO_Set_Pins(USART1);


	UART_Configuration_t UART_CFG;
	UART_CFG.UART_MODE = UART_MODE_Tx_Rx;
	UART_CFG.UART_Payload_length = UART_Payload_length_8B;
	UART_CFG.UART_Num_Stop_Bits = UART_Num_Stop_Bits_one_bit;
	UART_CFG.UART_Parity = UART_Parity_NONE;
	UART_CFG.UART_BaudRate = UART_BaudRate_115200;
	UART_CFG.UART_HW_FLOW_CTL = UART_HW_FLOW_CTL_NONE;
	UART_CFG.UART_IRQ_Enable = UART_IRQ_Enable_RXNE;
	UART_CFG.UART_PF_IRQ_CallBack = UART_IRQ_CallBack;

	MCAL_UART_Init(USART1, &UART_CFG);
	MCAL_UART_GPIO_Set_Pins(USART1);


	/* Loop forever */
	while(1)
	{

//		MCAL_UART_ReceiveData(USART1, &ch, enable);
//		MCAL_UART_SendData(USART1, &ch, enable);

	}
}

void UART_IRQ_CallBack(void)
{
	MCAL_UART_ReceiveData(USART1, &ch, disable);
	MCAL_UART_SendData(USART1, &ch, enable);
}


void Clock_Init()
{
	//open clock of AFIO
	RCC_AFIO_CLK_EN();

	//open clock of GPIOA
	RCC_GPIOA_CLK_EN();

	//open clock of GPIOB
	RCC_GPIOB_CLK_EN();
}
